name: 🪄 Update GitHub Activity

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 🧩 Generate activity feed
        uses: Readme-Workflows/recent-activity@v2.7.1
        with:
          GH_USERNAME: stefanstan2402
          MAX_LINES: 5
